# Generated by Django 5.2.7 on 2025-11-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book'), ('can_edit', 'Can edit book'), ('can_create', 'Can create book'), ('can_delete', 'Can delete book')]},
        ),
    ]
