# Generated by Django 5.2.9 on 2025-12-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
